"""added is_read field

Revision ID: 63c20796d889
Revises: ac26ded8f40a
Create Date: 2026-06-01 20:26:42.337534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c20796d889'
down_revision = 'ac26ded8f40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
