"""added is_read field

Revision ID: ac26ded8f40a
Revises: 
Create Date: 2026-06-01 17:10:15.310990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac26ded8f40a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
